name: CI  # This is the name of your workflow

on: [push, pull_request]  # This defines the events that will trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Updated to the latest version at the time of writing

    - name: Setup Node.js
      uses: actions/setup-node@v3  # Updated to the latest version at the time of writing
      with:
        node-version: '20'  # Updated to use Node.js 20

    - name: Install dependencies
      run: npm install  # Install your project dependencies
      
    - name: Run tests
      run: npm test  # Replace this with your test command
